### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by skbalahere** [Webiks/kibana-API#13]
I am trying to install this API for the kibana ver 5.5.1 but am getting error of version problem. It is expecting 5.5.0.

Is there any alternative to fix the issue

**Comment by ytzlax** [comment]
Hi,
I added 5.5.1 release, please reinstall 
./bin/kibana-plugin install https://github.com/Webiks/kibana-API/releases/download/5.5.1/kibana_api-0.1.0.zip
