### ISSUE TITLE
Version 6.0.1

### ISSUE THREAD

**Issue by vladan-me** [Webiks/kibana-API#24]
Hi, thanks for the plugin. I've tried to fork it and just change package.json so it can work with 6.0.1 but I'm getting the error:
 Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

What I'm doing wrong?
https://github.com/vladan-me/kibana-API/releases

Maybe you can release it in the meanwhile.

Thanks

**Comment by ytzlax** [comment]
Done
