### ISSUE TITLE
Request New API related to kibana embedded object

### ISSUE THREAD

**Issue by jess-park** [Webiks/kibana-API#25]
Hi, thanks for the API plug-in.
It is extremely effective way to visualize data source :)

**Change the embedded(iframe) dashboard based on parameterized date(From,  To)**
I think new API would be helpful which can apply date range to embedded dashboard and refresh with API.
We put some embedded dashboard and visualization. And we want to adjust period range which is attached on our UI date range controller. And after setting is done, we want to let embedded kibana object display data based on the modified date range.  
i.e.) ConfigureVisualizationByDate(from date, to date)

**Comment by ytzlax** [comment]
Done.
Look at https://github.com/Webiks/kibana-API/wiki/Time-function
you need to download the next relase its only on kibana 6.0.0:
./bin/kibana-plugin install https://github.com/Webiks/kibana-API/releases/download/6.0.0_0.3.0/kibana_api-0.3.0.zip
