### ISSUE TITLE
How to create visualization dynamically

### ISSUE THREAD

**Issue by nierjeshkumar** [Webiks/kibana-API#33]
Hi team,

I want to use API in my script so that I can create visualization dynamically. I have already created a script by which i am able to create index pattern dynamically now I want to use that index pattern further so that i can create visualization dynamically.
So I have apache-access* index pattern(created through script) now how i can use this index pattern to create visualization dynamically?
Please help.

Also I installed the Kibana API plugin then restart the service but still i m not able to see Kibana API in Kibana tool??

**Comment by ytzlax** [comment]
Hi,
Did you create the index-pattern by kibana-API plugin?

**Comment by nierjeshkumar** [comment]
Hi @ytzlax ,
No, I did not create index-pattern by kibana plugin and I dont see any error in logs.

**Comment by ytzlax** [comment]
How did you install the plugin?

**Comment by ytzlax** [comment]
Closes due to inactivity
