### ISSUE TITLE
Support for elastic v 6.3

### ISSUE THREAD

**Issue by WaleedAli007** [Webiks/kibana-API#34]
Hello,

Thank you guys for such an awesome plugin. 
**I am already using it with elastic v6.1** and was just wondering if the same version of this plugin is compatible with **elastic v6.3**? and if not what are your plans to release that **(for v6.3)**?

**Comment by ytzlax** [comment]
Hi,
Happy to hear that the plugin is useful for you.

I will check the 6.3 version in the next days, until that, you can simply download the 6.2.4 version, and change the version in the package. json file to 6.3.x, and check yourself if it's work

**Comment by ytzlax** [comment]
Done
