### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by YonatanKra** [Webiks/kibana-API#4]
It seems the documentation isn't finished.
A few tips here:
- Add comments to the `JSON` config examples or an explanation regarding what each line does.  It would make it clearer to users.
- Add a full code example with screenshots of what happens (unless you can setup a live demo which might be better). So here https://github.com/Webiks/kibana-API/wiki/Add-Visualization I'd add a full code on how to use the plugin:
```
// import or require the plugin
import * as myPlugin from ... (or require);

// Use the plugin
// set some x that would set the ___ as a ___ (for instance, would set a pie chart with certain params)
const x = {};
// initiate the call
myPlugin.someMethod(x);
...
```

So a user would be able to follow step by step on how to use the plugin.

**Comment by xycloud** [comment]
+1. I also dont know how to use this plugin, its awesome when providing a step-by-step

**Comment by ytzlax** [comment]
Hi, YonatanKra and xycloud , please look at https://github.com/Webiks/kibana-API#how-to-use
