### ISSUE TITLE
Delete visualisation feature

### ISSUE THREAD

**Issue by ytzlax** [Webiks/kibana-API#6]
Add delete visualisation feature

**Comment by rhautefeuille** [comment]
+1 :)

**Comment by ytzlax** [comment]
Hi, please tell me why you need this feature?

**Comment by rhautefeuille** [comment]
I would like the user to choose which secondary visualizations (if any) to display next to the main one, for instance with a multi-selection dropdown in the header of my page.
If he first selects 3 visualizations and then removes one, I need a way to make it disapear.
Does it make sense?

**Comment by ytzlax** [comment]
Delete visualisation meaning delete visualisation from .kibana index, I think you need to disappear the visualisation from the dashboard, look at https://github.com/Webiks/kibana-API/issues/20
I think it's will help you, if not let me know.

**Comment by rhautefeuille** [comment]
👍yes this is exactly what I want to acheive
it doesn't seem to be working though.
I replied on the other thread
